scripts/pytryout: pip search got deprecated
$ pip search package
ERROR: XMLRPC request failed [code: -32500]
RuntimeError: PyPI's XMLRPC API has been temporarily disabled due to
unmanageable load and will be deprecated in thenear future.
See https://status.python.org/ for more information.

Signed-off-by: Maciej Barć <xgqt@protonmail.com>